### ISSUE TITLE
How to add notification icon in second viewpager header ie above icon[this is not an issue]

### ISSUE THREAD

**Issue by veerastha** [AtomicSpider/Tinder-Like-Action-Bar#2]
Hi, can you please tell me how to add relative layout[or textview with background to show count in second viewpager header] instead of adding only icon to the tab header (this is not an issue just question to know how to do it)

**Comment by AtomicSpider** [comment]
Hi,
I've developed this using https://github.com/Mirkoddd/TabBarView
Which basically adds a custom view in place of actionbar. So you should be able to add any view to that place. Check out the TabBarView Repo and it's classes.
I haven't tried it myself but I'm pretty sure it's possible.

**Comment by veerastha** [comment]
hmm okay thanks.
